### ISSUE TITLE
Skia backend for GNU+Linux

### ISSUE THREAD

**Issue by ghost** [LibreSprite/LibreSprite-proposals#1]
Aseprite unfortunately went proprietary before implementing the Skia backend for GNU+Linux. In my opinion, this has to be one of the biggest priorities of the fork.

**Comment by nanoslayer** [comment]
Another alternative would be to migrate to Allegro 5. I've managed to build LibreSprite using [Allegro Legacy](https://github.com/NewCreature/Allegro-Legacy) in the past. This would allow us to port LibreSprite to Allegro 5 slowly. This could also allow us to build the LibreSprite Allegro4 backend on MacOS.

One of the main problems with Skia is that its build process is really complicated and messy.
