### ISSUE TITLE
Which language should LibreSprite support for scripting?

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite-proposals#13]
On LibreSprite/LibreSprite-proposals#9 there is a discussion about which language (and how many languages) LibreSprite should support for scripting, hence the separate issue.

As for now, LibreSprite runs javascript scripts, but I agree with @maujin111 and @jjhaggar when they say LibreSprite should support Lua as it's an easy programming language suited for the end user.

Personally, I find javascript very confusing, not the best language when it comes down to simplicity. Since @felipemanga said that "[supporting both is a pain](https://github.com/LibreSprite/LibreSprite/issues/160#issuecomment-909176907)", I'm way more inclined to pick Lua between the two, as it's less work for us and an easier approach for whoever wants to contribute.
Also, this will make adapting Aseprite scripts (written in Lua) easier, meaning more compatibility. A thing we should aim for

**Comment by felipemanga** [comment]
Now, there is very little overhead in terms of code maintenance. A new scripting language can be added in a few hours of work. New API's can be added and they automatically support all languages at once. Also, each language (other than Duktape) is entirely optional, so it should never be a hindrance. 

With the incoming PRs we'll soon have options that have their own strengths:
- Duktape is small and available everywhere
- V8 is *fast* and supports modern JS+Webassembly.
- Lua... it reminds me of the moon, I guess?)

If file size becomes a problem, we could consider having a lite version and a full one.
