### ISSUE TITLE
Compile AppImage for 32-bit

### ISSUE THREAD

**Issue by MintStudios** [LibreSprite/LibreSprite-proposals#19]
Linux, to me, is a reviver. For an old laptop, it can extend its life by a lot. And, old computers are generally 32 bit. I'm not a travisCI or Linux expert, but I think we can build a 32-bit AppImage as well.

Again, I haven't used travisCI, but is compiling for Windows possible?

**Comment by maujin111** [comment]
The current appimage in theory should support 32bit systems, could someone please confirm it?

**Comment by EchedelleLR** [comment]
Should I build it from scratch or try the one which says x86_64 ?

I already tested that one built in the last pre-release and it is incorrect, I supply terminal output:
```
echedey@echedey-devuan-vm:~/Downloads$ ./libreSprite-x86_64-pre-release.AppImage
bash: ./libreSprite-x86_64-pre-release.AppImage: cannot execute binary file: Exec format error
```

I see it as ELF x86_64 executable:
```
echedey@echedey-devuan-vm:~/Downloads$ file ./libreSprite-x86_64-pre-release.AppImage 
./libreSprite-x86_64-pre-release.AppImage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=2b28c9d62013e6b5542a1920e2bcc440fa19b8b1, stripped
```

**Comment by maujin111** [comment]
@EchedeyLR could you build it from scratch?

**Comment by EchedelleLR** [comment]
I checked dependencies: my testing system is based on Debian 10 (current oldstable but supported perfectly) and doesn't have liblua5.4-dev, only liblua5.3-dev.

**Comment by maujin111** [comment]
> I checked dependencies: my testing system is based on Debian 10 (current oldstable but supported perfectly) and doesn't have liblua5.4-dev, only liblua5.3-dev.

liblua5.3-dev should work too

**Comment by EchedelleLR** [comment]
Okay, I will try. Thank you.

**Comment by EchedelleLR** [comment]
It seems to work perfectly after building.

To get data about the OS:
```
echedey@echedey-devuan-vm:~/Documents/Builds/LibreSprite/build$ cat /etc/os-release
PRETTY_NAME="Devuan GNU/Linux 3 (beowulf)"
NAME="Devuan GNU/Linux"
VERSION_ID="3"
VERSION="3 (beowulf)"
VERSION_CODENAME=beowulf
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"
```

**Comment by EchedelleLR** [comment]
Are there instructions about how to build the AppImage ?

**Comment by maujin111** [comment]
Could you send me a zip folder?, maurial593@gmail.com, so I can do it

**Comment by EchedelleLR** [comment]
Compressing the `build` folder just enough right?

**Comment by maujin111** [comment]
yes please

**Comment by EchedelleLR** [comment]
The size exceeds the maximum allowed, it is like 180 MB.

**Comment by EchedelleLR** [comment]
I can upload it to a Nextcloud instance tomorrow with the college's internet connection which is through optic fiber.

**Comment by maujin111** [comment]
That would be great, thank you

**Comment by EchedelleLR** [comment]
@maujin111 it took 40-50 minutes but I could upload it at home.

I already sent the link to your email address.

**Comment by EchedelleLR** [comment]
@maujin111 when you check it, could you confirm that you received it correctly?

**Comment by maujin111** [comment]
@EchedeyLR Thank you very much for the files, could you please test the appimage for x86?. 
https://github.com/LibreSprite/LibreSprite/releases/tag/v1.0-beta.1

**Comment by EchedelleLR** [comment]
To avoid confusion I would call them x86_32 and x86_64 which are more standard names in comparison with x86 and x64 which were promoted by MicroSoft and doesn reflect the reality.

**Comment by EchedelleLR** [comment]
The file generated is still for x86_64, I think there is something wrong with the AppImage building itself.

![2021-09-30_08-27](https://user-images.githubusercontent.com/56733813/135406952-18531239-ba27-4f3b-a35d-615ff5cfa065.png)

Edited:

Both AppImage builds are x86_64.

![2021-09-30_08-30](https://user-images.githubusercontent.com/56733813/135407453-82337798-9e9a-4585-ba47-e7f59246ef1d.png)

**Comment by maujin111** [comment]
> The file generated is still for x86_64, I think there is something wrong with the AppImage building itself.
> 
> ![2021-09-30_08-27](https://user-images.githubusercontent.com/56733813/135406952-18531239-ba27-4f3b-a35d-615ff5cfa065.png)
> 
> Edited:
> 
> Both AppImage builds are x86_64.
> 
> ![2021-09-30_08-30](https://user-images.githubusercontent.com/56733813/135407453-82337798-9e9a-4585-ba47-e7f59246ef1d.png)

I see, the problem is when the appimage is created, let me create a VM to compile everything

**Comment by Zughy** [comment]
Done in 1.0 (https://github.com/LibreSprite/LibreSprite/releases/tag/v1.0), closing
