### ISSUE TITLE
Unbundle/unfork libraries

### ISSUE THREAD

**Issue by davexunit** [LibreSprite/LibreSprite-proposals#20]
Since this is a promising community fork of a now-proprietary project that presumably isn't hostile to GNU/Linux distributions, I'd really like to see this fork address a major packaging issue: The use of bundled and forked libraries.  Bundled dependencies degrade the usefulness of package managers and open the user up to unpatched security vulnerabilities.

Most notably, the entire Allegro 4 source code is contained here with a few patches thrown in on top.  Allegro 5 is a new API, so I imagine upgrading would be difficult, but perhaps there is a way to unfork Allegro 4 (does upstream still accept patches?) so that users can use the package provided by their distribution.

Furthermore, there are lots of submodules in here for bundled source code of third party libraries.  I think these should all be removed and the build system should use what the system provides.  The build system currently allows _some_ libraries to used from the system, but you have to set a build flag explicitly for each one, which I feel is backwards.  To illustrate, this is what the GNU Guix package for Aseprite 1.1.1 looks like:

``` scheme
(define-public aseprite
  (package
    (name "aseprite")
    (version "1.1.1")
    ;; The release tarball isn't good enough because it's missing some
    ;; necessary code that is only in git submodules.
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/aseprite/aseprite.git")
                    (commit "v1.1.1")
                    (recursive? #t)))
              (sha256
               (base32
                "1yr0l3bc68lyrffrzxgw98zznv8yz5ldl98lyvp6s5grny4s4jyk"))))
    (build-system cmake-build-system)
    (arguments
     '(#:configure-flags
       ;; Use shared libraries instead of building bundled source.
       (list "-DWITH_WEBP_SUPPORT=1"
             "-DUSE_SHARED_CURL=1"
             "-DUSE_SHARED_GIFLIB=1"
             "-DUSE_SHARED_JPEGLIB=1"
             "-DUSE_SHARED_ZLIB=1"
             "-DUSE_SHARED_LIBPNG=1"
             "-DUSE_SHARED_LIBLOADPNG=1"
             "-DUSE_SHARED_LIBWEBP=1"
             "-DUSE_SHARED_TINYXML=1"
             "-DUSE_SHARED_PIXMAN=1"
             "-DUSE_SHARED_FREETYPE=1"
             "-DUSE_SHARED_ALLEGRO4=1"
             "-DENABLE_UPDATER=0" ; no auto-updates
             (string-append "-DFREETYPE_INCLUDE_DIR="
                            (assoc-ref %build-inputs "freetype")
                            "/include/freetype2"))))
    (native-inputs
     `(("pkg-config" ,pkg-config)))
    ;; TODO: Use a patched Allegro 4 that supports window resizing.  This
    ;; patched version is bundled with Aseprite, but the patches should be
    ;; extracted and applied on top of a standalone Allegro 4 package.
    (inputs
     `(("allegro" ,allegro-4)
       ("curl" ,curl)
       ("freetype" ,freetype)
       ("giflib" ,giflib)
       ("libjpeg" ,libjpeg)
       ("libpng" ,libpng)
       ("libwebp" ,libwebp)
       ("libx11" ,libx11)
       ("libxext" ,libxext)
       ("libxxf86vm" ,libxxf86vm)
       ("pixman" ,pixman)
       ("tinyxml" ,tinyxml)
       ("zlib" ,zlib)))
    (synopsis "Animated sprite editor and pixel art tool")
    (description "Aseprite is a tool for creating 2D pixel art for video
games.  In addition to basic pixel editing features, Aseprite can assist in
the creation of animations, tiled graphics, texture atlases, and more.")
    (home-page "http://www.aseprite.org/")
    (license license:gpl2+)))
```

http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/game-development.scm#n401

I'm not familiar with the Aseprite codebase itself, I'm just a lowly packager, so I hope that the people that are going to steer this project can help make it easier for distributions to provide quality Aseprite packages.

**Comment by nanoslayer** [comment]
This can probably be closed. The only remaining bundled libraries are:

* Allegro 4: slated to be replaced soon
* simpleini, loadpng, modp_b64: not widely available in package repositories
* duktape
