### ISSUE TITLE
Packaging for Linux

### ISSUE THREAD

**Issue by MintStudios** [LibreSprite/LibreSprite-proposals#22]
One of the biggest pros of Linux is the terminal. To install software, one will just `sudo apt install ____`. (for Debian-based distros ofc) As we all know, LibreSprite has an AppImage. I was thinking, what if we could produce native packages for major distros? This would be Arch, Debian, and Fedora-based distros. We could use Github packages (I haven't deeply looked into that yet), or something else. For the average Linux user who uses the terminal a lot, this would be easier than downloading an AppImage.  (Probably)

**Comment by Zughy** [comment]
Kind of a stale issue, closing
