### ISSUE TITLE
Migrate to Allegro 5

### ISSUE THREAD

**Issue by nanoslayer** [LibreSprite/LibreSprite-proposals#25]
We might be able to port LibreSprite to Allegro 5.

There is a library called [Allegro Legacy](https://github.com/NewCreature/Allegro-Legacy) that re-implements the Allegro 4 API on top of Allegro 5. That could allow us to slowly port LibreSprite to Allegro 5. In theory, we might also be able to build LibreSprite on macOS with Allegro Legacy. We can also take advantage of some of Allegro 5's new features while keeping the rest of the codebase intact: we could replace the current input polling behavior with Allegro 5's event loop.

See also: #1

**Comment by Zughy** [comment]
We're probably gonna migrate to SDL2, and some tests are already being done https://github.com/felipemanga/LibreSprite/tree/sdl2-backend, feel free to check them! Quoting from Matrix/Discord "now the only thing left is to figure out how transparent blitting is supposed to work and it'll be in a usable state"

**Comment by nanoslayer** [comment]
I was able to build the SDL2 backend (after I made some changes to the CMake files). However, from what I can tell it seems that SDL2 doesn't support transparent blitting. We might be able to use an external library like [SDL_gfx](https://www.ferzkopp.net/Software/SDL_gfx-2.0/Docs/html/index.html), however. It provide a [SDL_gfxBlitRGBA](https://www.ferzkopp.net/Software/SDL_gfx-2.0/Docs/html/_s_d_l__gfx_blit_func_8h.html#ab49c560e89b8305051b2e6b347215f03) function, which seems like it could achieve the desired effect.

Perhaps we should open an issue to track progress on the SDL2 backend.

@felipemanga

**Comment by felipemanga** [comment]
SDL2 supports transparent blitting, but not with pre-multiplied alpha in the software renderer. I still have to try with hardware acceleration, it might work there.

**Comment by nanoslayer** [comment]
I'm closing this for now as the SDL2 port seems more promising.

We should open a new issue for the SDL2 port.
