### ISSUE TITLE
Feature freeze before every stable release

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite-proposals#26]
In order to avoid any big mess (mistakes can happen) and risk to publish a stable version which is not stable, it'd be nice to define a period of time that kicks in when every milestone (e.g. `1.0`) is completed and we feel ready for the actual release. In here, no "feature" PR will be merged, hence the name "feature freeze", so we can completely focus on testing and bug solving. Otherwise, we might implement a new feature - especially if big - a couple days before the stable release, only to discover that there is a major issue after the release is already available for everyone.

This *does not* mean people can't suggest features and/or create PRs adding new features in the meanwhile. Just, that those features won't be added into the upcoming stable version.

A feasible period could be two weeks.

Thoughts?

**Comment by felipemanga** [comment]
As proposed, a feature freeze might have a negative impact as useful PRs would get turned away.
I'd suggest that once master is feature complete, a release branch is made. Feature PRs would still be accepted into master. After that, there are two options:
- Accept bug fixes into master, cherrypick them into the release branch.
- Accept bug fixes into the release branch, once the release is "live", this branch is merged back into master.

**Comment by Zughy** [comment]
> a feature freeze might have a negative impact as useful PRs would get turned away.

No no, it doesn't mean they can't be approved. They can, just, they'll have to wait till the stable release rolls out to be merged



> * Accept bug fixes into master, cherrypick them into the release branch.
> 
> * Accept bug fixes into the release branch, once the release is "live", this branch is merged back into master.

I smell trouble (and more work for maintainers)

**Comment by felipemanga** [comment]
For a moment I thought you'd be turning down unrelated PRs.
So approved PRs would just sit there waiting for master to stabilize?
What is the next release's feature list?

**Comment by Zughy** [comment]
In theory is this => https://github.com/LibreSprite/LibreSprite-proposals/milestone/1, which is empty because the MacOS issue is in the other repo (it's basically a feature because it's never worked but whatever) and because we're still not sure about the new backend (even if I guess is 99% SDL2). I'd personally avoid to add other features this time

**Comment by Zughy** [comment]
Well, it's already happening, closing
