### ISSUE TITLE
SDL2 backend instead of Allegro/Skia

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite-proposals#28]
##### Is your feature request related to a problem? Please describe
Allegro4 is outdated and Skia is a nightmare to compile (bonus: it's Google)

##### Describe the solution you'd like
SDL2 backend. Contributors are already working on it, doing a great job (a lot of things already work)

##### Describe alternatives you've considered
We've already discussed alternatives in #1 (which this issue supersedes), with SDL2 looking like the best option

**Comment by ghost** [comment]
I have a [WIP branch](https://github.com/nanoslayer/LibreSprite/tree/sdl2-only) which removes most of the code that won't be needed once the SDL2 backend is complete.

**Comment by Zughy** [comment]
Implemented in https://github.com/LibreSprite/LibreSprite/pull/215
