### ISSUE TITLE
Bump to C++14

### ISSUE THREAD

**Issue by felipemanga** [LibreSprite/LibreSprite-proposals#29]
Currently, LibreSprite compiles under C++11 and targets GCC 4.8 on Linux.
I don't think anyone still uses such an ancient version of GCC (my distro comes with 11.1), so there is no negative impact in bumping the language to 14.
On the other hand, there are negatives in staying with 11: numerous optimizations are limited or unavailable (constexpr was hard to use in 11, no move in lambda capture lists) and newer libraries like V8 won't compile without 14 as a minimum.

Alternatively, if we want to make the most of the change, we could go all the way to C++17.

**Comment by Zughy** [comment]
I'd be more cautious and stick with c++ 14
