### ISSUE TITLE
Thread management

### ISSUE THREAD

**Issue by felipemanga** [LibreSprite/LibreSprite-proposals#30]
Currently the code uses native threads directly, instead of std::thread, and it does so without a queue. Whenever it needs something to be done asynchronously, it spawns a new thread and uses a timer on the main thread to keep polling the worker
to see if it has finished its job.

Given that threads are a limited system resource and std::thread provides a standard and platform-independent implementation, I'd like to propose the use of a task manager based on std::thread. 
This would create a set amount of threads (say, 8) and put tasks in a queue until a thread is available. 
Once done, the result will be handed over to a callback, removing the need for multiple timers and polling. 
The task manager would also allow cancelling a pending or in-progress task.

**Comment by Zughy** [comment]
Current thread spamming doesn't sound like a nice thing to do. +1

**Comment by felipemanga** [comment]
This is the public interface of the TaskManager:
```cpp
namespace base {
  // Used for checking if a task is done or for telling it to stop early
  class TaskMonitor {
  public:
    bool done(); // true = task has been completed
    void abort(); // tell task to stop and throw away result
  };

  class TaskManager {
  public:
    static TaskManager& instance(); // This class is a singleton

    // calls callback on the next update cycle
    void delayed(std::function<void()> callback); 

    // calls worker in a thread, forwards the resulting Data to consumer in the main thread, 
    // aborter may be called from the main thread and should signal to the worker that it needs to stop quickly. 
    template<typename Data>
    TaskMonitor addTask(std::function<Data()>&& worker, std::function<void(Data)>&& consumer, std::function<void()>&& aborter);

    // calls producer in a thread. Producer can then generate multiple Data results by calling onProduce.
    // calls consumer multiple times on the main thread
    // aborter may be called on the main thread and should signal to the producer that it needs to stop quickly.
    template<typename Data>
    TaskMonitor addProducer(std::function<void( std::function<void(Data)>onProduce )>&& producer, 
                                              std::function<void(Data)>&& consumer,
                                              std::function<void()>&& aborter);
  };
}
```

**Comment by felipemanga** [comment]
I ended up not having an "addProducer" method. Having a lambda that got another lambda as a parameter was starting to look like lisp.
Instead, there's an addTask variant that accepts an "isAlive" parameter. The task will be called repeatedly, until isAlive is set to false.
