### ISSUE TITLE
V8 scripting engine

### ISSUE THREAD

**Issue by felipemanga** [LibreSprite/LibreSprite-proposals#32]
This is a Javascript engine that is much better than Dukscript. Embedding it as the primary engine when possible, and falling back
to Dukscript otherwise, would allow scripts to run much more quickly. It does not significantly impact the final binary size nor does its presence cause the code to become cluttered or harder to maintain.

**Comment by Zughy** [comment]
(you mean Duktape I guess)

> Embedding it as the primary engine when possible

A practical example where it can't be possible?

**Comment by felipemanga** [comment]
Yes, Duktape. :man_facepalming: 
The only situations I can think of is emscripten (where we'd want to use the browser's own engine instead) and if someone making a custom build simply doesn't want to install that dependency.

**Comment by ghost** [comment]
Do we really need 3 different scripting engines? I'd rather we choose one and stick with it. That way the community isn't fragmented.

**Comment by felipemanga** [comment]
I would be happy with just V8. In practice, a regular release build would have 2, Javascript (through v8) and Lua, 
I don't see how that would fragment the community.
