### ISSUE TITLE
Roadmap: propose what you'd like to see

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite-proposals#9]
As the development is back on track (just compare commits of this month with the other ones), a roadmap can help us avoid derailing and getting lost. As discussed on Discord/Matrix, each maintainer/contributor/user can list 3 points about what they think should be prioritised  for the 1.0 release (currently LibreSprite says "1.0-dev"), so to have a wider perspective of both users needs and development musts.
This is **not** a contest, meaning that the most voted feature won't necessarily be implemented (e.g. development issues, troll votes). Because of that, maintainers reserve the final decision.

I'll start:
- **[Back-end] get rid of Allegro 4 and use SDL2 instead**: right now there are bugs we simply can't solve, because they're part of the current back-end (Allegro 4). Aseprite stuck with Skia, but everybody seems to somehow dislike it (including me). According to an SDL2 expert (https://github.com/LibreSprite/LibreSprite/issues/2#issuecomment-906817056), this last one is not just viable, but even better than Skia. As for now, @felipemanga is doing some testing in his own fork https://github.com/felipemanga/LibreSprite/tree/sdl2-backend. If this works, it'll mean having a way easier life both for maintainers and contributors (with users benefiting consequently).
- **Mac support**: right now LibreSprite only works on Linux and Windows. The more (famous) OS we can cover, the more contributors we can have. This needs the previous point first, as it doesn't work with Allegro 4.
- **More default palettes**: as the first two points are technical, I've felt like leaving the last one more artistic-driven. LibreSprite doesn't currently have so many artistic palettes, and something like LibreSprite/LibreSprite-proposals#4 can make a lot of artists (amateurs and not) very happy

**Comment by nanoslayer** [comment]
I'd like to see a better command-line interface for exporting spritesheets. The current one is somewhat inelegant.

**Comment by Zughy** [comment]
Closing this as 1.0 is kind of ready. I'll open a new issue for 1.1 when the former is out in the open
